# Generated by Django 6.0.5 on 2026-06-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('AWAITING_VERIFICATION', 'Awaiting Verification'), ('PAID', 'Payment Verified'), ('FAILED', 'Failed / Rejected'), ('REFUNDED', 'Refunded')], default='UNPAID', max_length=30),
        ),
    ]
