# Generated by Django 6.0.5 on 2026-06-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variant_image',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
