# Generated by Django 6.0.5 on 2026-06-23 13:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0003_guest_cart_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guest_token', models.UUIDField(blank=True, help_text='For guest checkouts', null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PAYMENT_PENDING', 'Payment Pending'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=20)),
                ('shipping_province', models.CharField(max_length=100)),
                ('shipping_district', models.CharField(max_length=100)),
                ('shipping_city', models.CharField(max_length=100)),
                ('shipping_street', models.CharField(max_length=255)),
                ('shipping_instructions', models.TextField(blank=True, default='')),
                ('shipping_rule_title', models.CharField(max_length=255)),
                ('transit_days_min', models.PositiveIntegerField(default=0)),
                ('transit_days_max', models.PositiveIntegerField(default=0)),
                ('processing_days_max', models.PositiveIntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('shipping_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('COD', 'Cash on Delivery'), ('ONLINE', 'Online Payment')], max_length=20)),
                ('payment_id', models.CharField(blank=True, default='', help_text='External gateway transaction ID', max_length=255)),
                ('payment_metadata', models.JSONField(blank=True, default=dict)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_sessions', to='cart.cart')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
