# Generated by Django 6.0.5 on 2026-06-23 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkout', '0001_initial'),
        ('orders', '0001_initial'),
        ('shipping', '0002_shippingrule_transit_days_max_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutsession',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_session', to='orders.order'),
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='shipping_rule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='shipping.shippingrule'),
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
