# Generated by Django 6.0.5 on 2026-06-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutsession',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('BANK', 'Bank Transfer'), ('ESEWA', 'eSewa'), ('KHALTI', 'Khalti'), ('ONLINE', 'Online Payment')], max_length=20),
        ),
    ]
