# Generated by Django 6.0.5 on 2026-06-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_alter_checkoutsession_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutsession',
            name='payment_method',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
