# Generated by Django 6.0.5 on 2026-06-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_active',
        ),
        migrations.AddField(
            model_name='cart',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='guest_token',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('CHECKED_OUT', 'Checked Out'), ('EXPIRED', 'Expired'), ('MERGED', 'Merged'), ('ABANDONED', 'Abandoned')], db_index=True, default='ACTIVE', max_length=20),
        ),
    ]
