# Generated by Django 6.0.5 on 2026-06-25 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_guest_cart_support'),
        ('catalog', '0007_remove_productvariant_color_productvariant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='selected_media',
            field=models.ForeignKey(blank=True, help_text='The specific product image the customer selected', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.productmedia'),
        ),
    ]
