# Generated by Django 6.0.5 on 2026-06-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='payment_type',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('BANK', 'Bank Transfer'), ('ESEWA', 'eSewa'), ('KHALTI', 'Khalti'), ('MANUAL', 'Manual Payment'), ('GATEWAY', 'Gateway Payment')], max_length=20),
        ),
    ]
