# Generated by Django 6.0.5 on 2026-06-23 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial_shipping_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingrule',
            name='transit_days_max',
            field=models.PositiveIntegerField(default=5, help_text='Maximum days for transit (excluding processing time).'),
        ),
        migrations.AddField(
            model_name='shippingrule',
            name='transit_days_min',
            field=models.PositiveIntegerField(default=3, help_text='Minimum days for transit (excluding processing time).'),
        ),
        migrations.AlterField(
            model_name='shippingrule',
            name='estimated_days',
            field=models.CharField(blank=True, default='3-5 Business Days', help_text='Legacy display string (Source of truth for Phase 1).', max_length=50),
        ),
    ]
