# Generated by Django 6.0.5 on 2026-06-23 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_brand_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='processing_days_max',
            field=models.PositiveIntegerField(default=0, help_text='Maximum days to process order for this product.'),
        ),
        migrations.AddField(
            model_name='product',
            name='processing_days_min',
            field=models.PositiveIntegerField(default=0, help_text='Minimum days to process order for this product.'),
        ),
    ]
