# Generated by Django 6.0.5 on 2026-06-12 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_brand_product_brand'),
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='catalog.brand'),
        ),
    ]
