# Generated by Django 6.0.5 on 2026-06-13 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_promotion_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='promotion_type',
            field=models.CharField(choices=[('BANNER', 'Visual Banner'), ('CAMPAIGN', 'Marketing Campaign'), ('EXCLUSIVE', 'System Exclusive')], default='CAMPAIGN', max_length=20),
        ),
    ]
