# Generated by Django 6.0.5 on 2026-06-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_promotion_promotion_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='promotion_type',
            field=models.CharField(choices=[('BANNER', 'Visual Banner'), ('CAMPAIGN', 'Marketing Campaign'), ('SYSTEM', 'System Automated'), ('EXCLUSIVE', 'System Exclusive')], default='CAMPAIGN', max_length=20),
        ),
    ]
